on:
  push:
  pull_request:

jobs:
  bp:
    runs-on: ubuntu-latest
    name: Build project
    steps:

    - name: checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install blueprint apt deps with cache
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: graphviz libgraphviz-dev pandoc texlive-full texlive-xetex
        version: 1.0

    - name: Install blueprint deps
      run: |
        mktexmf --all
        pip install invoke git+https://github.com/plastex/plastex.git git+https://github.com/PatrickMassot/leanblueprint.git

    - name: Build blueprint PDF
      run: |
        cd blueprint
        inv bp
      
