on:
  push:

jobs:
  update_lean_xyz_branch_and_build:
    runs-on: ubuntu-latest
    name: Build project
    steps:

    - name: checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

#     - name: build project
#       uses: leanprover-contrib/lean-build-action@master
      
    - name: doc-gen - install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
        ~/.elan/bin/lean --version
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: doc-gen - install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: doc-gen - checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: leanprover-community/doc-gen
        path: doc-gen
        
    - name: doc-gen - install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r doc-gen/requirements.txt
        ls doc-gen
        
    - name: doc-gen - mangle paths
      run: |
        mathlib_git_hash="$(sed '/rev/!d;s/.*"\([a-z0-9]*\)".*/\1/' leanpkg.toml)"
        cd doc-gen
        sed -i "s/rev = \"\S*\"/rev = \"$mathlib_git_hash\"/" leanpkg.toml
        leanproject get-mathlib-cache
        echo -e "path ../src" >> leanpkg.path
        cat leanpkg.path
        (cd ../src;
        find "." -name \*.lean -not -name all.lean \
          | sed 's,^\./,,;s,\.lean$,,;s,/,.,g;s,^,import ,' \
          | sort >./all.lean)
          
        cat ../src/all.lean
        lean --path
  
    - name: doc-gen - run
      run: |
        cd doc-gen
        ls .
        lean -v
        echo Trying our file
        lean src/all.lean
        echo Trying the real thing
        lean src/entrypoint.lean
        
    - name: doc-gen - upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: export.json
        
