on:
  push:
    # branches-ignore:
    #   - blueprint
  pull_request:

jobs:
  update_lean_xyz_branch_and_build:
    runs-on: ubuntu-latest
    name: Build project
    steps:

    - name: checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: update branch
      if: github.ref == 'refs/heads/master'
      uses: leanprover-contrib/update-versions-action@master

    - name: Install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
        ~/.elan/bin/lean --version
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install leanproject
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        source ~/.profile
        pipx install mathlibtools

    - name: Set up olean cache
      uses: actions/cache@v3
      with:
        path: _cache
        key: oleans

    - name: Configure
      run: |
        leanpkg configure
        leanproject get-mathlib-cache
        leanproject get-cache --fallback=download-first || true

    - name: Build
      run: |
        set -o pipefail
        # TODO: allow noisy files in a better way
        lean --json --make src | (python3 _target/deps/mathlib/scripts/detect_errors.py || true)

    - name: Save olean cache
      run: |
        leanproject mk-cache

    - name: Export symbols
      run: |
        leanproject mk-all
        lean --run export.lean > lean-decl-info.tex

    - uses: actions/upload-artifact@v3
      with:
        name: lean-decl-info
        path: lean-decl-info.tex

    - name: Install blueprint apt deps with cache
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: graphviz libgraphviz-dev
        version: 1.0

    - uses: actions/cache@v3
      name: Tectonic Cache
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-
    - uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        biber-version: "latest"

    - name: Install blueprint deps
      run: |
        pip install invoke git+https://github.com/plastex/plastex.git git+https://github.com/PatrickMassot/leanblueprint.git

    - name: Build blueprint
      run: |
        inv all

    - name: Deploy blueprint
      if: contains('|refs/heads/master|refs/heads/blueprint|', github.ref)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.github_token }}
        # NOTE: web is inside docs/blueprint
        publish_dir: ./blueprint/web
        # NOTE: To avoid overwriting existing files in gh_pages, we deploy it to a subdirectory
        destination_dir: blueprint
      
